- name: clean up old container
  include: sonicdocker.yml
  vars:
    docker_container: docker-database
    docker_image: "{{ image_id_database }}"
    docker_state: absent


- name: Start the database docker container (redis-server)
  include: sonicdocker.yml
  vars:
    docker_container: database
    docker_image: "{{ image_id_database }}"
    docker_state: reloaded
    docker_log_driver: syslog
    # Prevent color control char to stdout
    docker_tty: no
#   docker_net: bridge
#   docker_host_address: "{{ remote_facts.ansible_facts.ansible_docker0.ipv4.address }}"

